name: Set up Python and Poetry
inputs:
  python-version:
    default: 3.11.9
  poetry-version:
    default: 1.8.2
outputs:
  python-path:
    value: ${{ steps.setup-python.outputs.python-path }}
  python-version:
    value: ${{ steps.setup-python.outputs.python-version }}
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
    # The default pipx paths on GitHub-hosted runners are locations that actions/cache cannot
    # write to, like /opt/pipx and "C:\Program Files (x86)\pipx". See
    # https://github.com/pypa/pipx/discussions/1051 for more info.
    - name: Set pipx paths
      id: set-pipx-paths
      run: |
        echo "PIPX_BIN_DIR=$HOME/.local/bin" >> "$GITHUB_ENV"
        echo "PIPX_HOME=$HOME/.local/pipx" >> "$GITHUB_ENV"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        echo "pipx-bin-dir=$HOME/.local/bin" >> "$GITHUB_OUTPUT"
        echo "pipx-home=$HOME/.local/pipx" >> "$GITHUB_OUTPUT"
      # Use bash so that $HOME is evaluated properly.
      shell: bash
    - name: Cache pipx
      id: cache-pipx
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.set-pipx-paths.outputs.pipx-bin-dir }}
          ${{ steps.set-pipx-paths.outputs.pipx-home }}
        key: pipx-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-poetry${{ inputs.poetry-version }}
    - name: Set up Poetry
      if: steps.cache-pipx.outputs.cache-hit != 'true'
      run: pipx install poetry==${{ inputs.poetry-version }} --python '${{ steps.setup-python.outputs.python-path }}'
