name: Set up Poetry
description: Install Poetry and cache its installation.
inputs:
  poetry-version:
    default: 1.8.2
runs:
  using: composite
  steps:
    - name: Get Python version
      id: get-python-version
      run: |
        if [ ! -d "$pythonLocation" ]; then
          echo "You must use the setup-python action before using this action."
          exit 1
        fi 
        "$pythonLocation/python" -c "import platform; print(f'python-version={platform.python_version()}')" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Set paths
      id: set-paths
      run: |
        echo "POETRY_BIN_DIR=$HOME/.local/poetry_bin" >> "$GITHUB_ENV"
        echo "POETRY_HOME=$HOME/.local/poetry" >> "$GITHUB_ENV"
        echo "poetry-bin-dir=$HOME/.local/poetry_bin" >> "$GITHUB_OUTPUT"
        echo "poetry-home=$HOME/.local/poetry" >> "$GITHUB_OUTPUT"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      # Use bash so that $HOME is evaluated properly.
      shell: bash
    - name: Cache poetry
      id: cache-poetry
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ${{ steps.set-paths.outputs.poetry-bin-dir }}
          ${{ steps.set-paths.outputs.poetry-home }}
        key: pipx-${{ runner.os }}-py${{ steps.get-python-version.outputs.python-version }}-poetry${{ inputs.poetry-version }}
    - name: Install Poetry (Linux/Mac)
      if: runner.os != "Windows" && steps.cache-pipx.outputs.cache-hit != 'true'
      run: |
        "$pythonLocation/python" -m venv "$POETRY_HOME"
        "$POETRY_HOME/bin/python" -m pip install poetry==${{ inputs.poetry-version }}
        ln -s "$POETRY_HOME/bin/poetry" "$POETRY_BIN_DIR/poetry"
      shell: bash
    - name: Install Poetry (Windows)
      if: runner.os == "Windows" && steps.cache-pipx.outputs.cache-hit != 'true'
      run: |
        "$pythonLocation/python" -m venv "$POETRY_HOME"
        "$POETRY_HOME/Scripts/python" -m pip install poetry==${{ inputs.poetry-version }}
        ln -s "$POETRY_HOME/bin/poetry.exe" "$POETRY_BIN_DIR/poetry.exe"
      shell: bash
    - name: Print Poetry version
      run: poetry --version
      shell: bash